# Generated by Django 4.2.16 on 2024-10-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_usersignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='user',
        ),
        migrations.AddField(
            model_name='usersignup',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='FirstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='LastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='Password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='Username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='dob',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Other')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='phone',
            field=models.IntegerField(default=''),
        ),
    ]
