# Generated by Django 4.2.16 on 2024-10-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_cart_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=100)),
                ('LastName', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default='')),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
