# Generated by Django 4.2.16 on 2024-10-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userinfo_city_userinfo_pincode_userinfo_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='FirstName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='LastName',
        ),
    ]
